ServerRoot "/usr/local/apache2"
Listen 10080
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule http2_module modules/mod_http2.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so

User daemon
Group daemon
ServerAdmin you@example.com
ServerName localhost
DocumentRoot "/usr/local/apache2/htdocs"
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

Protocols h2 http/1.1
H2Direct on

<VirtualHost *:10080>
    ServerName localhost
    DocumentRoot "/usr/local/apache2/htdocs"
    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/server.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/server.key"
    Protocols h2 http/1.1
</VirtualHost>
